trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: varcody  # Grupo de variables con credenciales de JFrog

steps:


# 🔹 Descargar dependencias desde Artifactory asegurando versión correcta
- script: |
   

    echo "📌 Configurando autenticación en JFrog Artifactory... EXPORT"
    
    # 📌 1️⃣ Verificar si `requirements.txt` existe
    if [ ! -f "requirements.txt" ]; then
        echo "❌ ERROR: No se encontró el archivo requirements.txt en el repositorio."
        exit 1
    fi
    echo "✅ requirements.txt encontrado."

    # 📌 2️⃣ Validar si las dependencias existen en JFrog antes de instalar
    echo "📌 Validando disponibilidad de dependencias en Artifactory..."
    MISSING_PACKAGES=()
    
    while IFS= read -r package; do
        package_name=$(echo "$package" | cut -d'=' -f1)  # Extraer solo el nombre del paquete
        PKG_URL="$(PACKAGE_URL)/${package_name}/"

        # Verificar si el paquete existe en JFrog Artifactory
        if ! curl --silent --fail -u $(JFROG_USERNAME):$(JFROG_PASSWORD) "$PKG_URL" > /dev/null; then
            echo "❌ $package_name NO existe en Artifactory"
            MISSING_PACKAGES+=("$package_name")
        else
            echo "✅ $package_name encontrado en Artifactory."
        fi
    done < <(grep -Eo '^[^#]+' requirements.txt | awk '{print $1}')

    # 📌 3️⃣ Si hay paquetes faltantes, detener el pipeline
    if [ ${#MISSING_PACKAGES[@]} -gt 0 ]; then
        echo "❌ ERROR: Las siguientes dependencias NO existen en Artifactory:"
        printf '%s\n' "${MISSING_PACKAGES[@]}"
        exit 1
    fi

    # 📌 4️⃣ Instalar dependencias desde Artifactory
    echo "📌 Instalando dependencias desde Artifactory..."
    pip install --no-cache-dir  --index-url=$(ARTIFACTORY_URL)  -r requirements.txt
  
    # 📌 5️⃣ Verificar instalación de todas las dependencias
    echo "📌 Verificando instalación de todas las dependencias..."
    while IFS= read -r package; do
        package_name=$(echo "$package" | cut -d'=' -f1)  # Extraer solo el nombre del paquete
        if pip list | grep -i "^$package_name "; then
            echo "✅ $package_name está instalado"
        else
            echo "❌ $package_name NO está instalado"
        fi
    done < <(grep -Eo '^[^#]+' requirements.txt | awk '{print $1}')
  displayName: 'Descargar e instalar dependencias desde Artifactory con autenticación'
