trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: varcody  # Grupo de variables con credenciales de JFrog

steps:


# 🔹 Descargar dependencias desde Artifactory asegurando versión correcta
- script: |
    echo "📌 Instalando dependencias desde Artifactory con autenticación..."

    echo "📌 Configurando autenticación en JFrog Artifactory... EXPORT"

    pip install --no-cache-dir  --index-url=$(ARTIFACTORY_URL)  -r requirements.txt
  
    echo "📌 Verificando instalación de todas las dependencias..."
    while IFS= read -r package; do
        package_name=$(echo "$package" | cut -d'=' -f1)  # Extraer solo el nombre del paquete
        if pip list | grep -i "^$package_name "; then
            echo "✅ $package_name está instalado"
        else
            echo "❌ $package_name NO está instalado"
        fi
    done < <(grep -Eo '^[^#]+' requirements.txt | awk '{print $1}')
  displayName: 'Descargar e instalar dependencias desde Artifactory con autenticación'
